package app.enums;

public enum AuditEventTypes {
    ACCESS_ALLOWED,
    ACCESS_DENIED,
    SUSPICIOUS_ACTIVITY,

    AUDIT_FAILURE,

    DELETE_ERROR,
    ENTITY_NOT_EXISTS,
    INVALID_STATE,
    SAVING_ERROR,
    VALIDATION_ERROR,
    IO_ERROR,

    SUCCESSFUL,
}
