package app.enums;

public enum OperationTypes {
    ADMIN_IP_BAN,

    ACCESS_ADMIN_AUDIT,
    ACCESS_ADMIN_DASHBOARD,
    ACCESS_ADMIN_IPBAN,
    ACCESS_ADMIN_LOGS,
    ACCESS_ADMIN_CACHE,
    ACCESS_ADMIN_EXTJOBS,

    ACCESS_PAGE_MAIN,
    ACCESS_PAGE_FILES,
    ACCESS_PAGE_FESTIVALS,
    ACCESS_PAGE_UPLOAD,

    ACCESS_PLACE_LIST,
    ACCESS_PLACE_ADD,
    ACCESS_PLACE_EDIT,

    ACCESS_ROLE_LIST,
    ACCESS_ROLE_CREATE,
    ACCESS_ROLE_EDIT,

    ACCESS_SESSION_HEARTBEAT,

    ACCESS_USER_LIST,
    ACCESS_USER_EDIT,
    ACCESS_USER_LOGIN,
    ACCESS_USER_LOGOUT,
    ACCESS_USER_PASSWORD,

    ACCESS_PAGE_ERROR,
    ACCESS_PAGE_STATIC,
    ACCESS_PAGE_UNKNOWN,

    CHANGE_FESTIVAL_ADD,
    CHANGE_FESTIVAL_EDIT,
    CHANGE_FESTIVAL_DELETE,
    CHANGE_PLACE_ADD,
    CHANGE_PLACE_EDIT,
    CHANGE_PLACE_DELETE,

    CHANGE_FILE_CREATE_PLACEHOLDER,
    CHANGE_FILE_UPLOAD_CHUNK,
    CHANGE_FILE_DELETE_PLACEHOLDER,
    CHANGE_FILE_PUBLISH,
    CHANGE_FILE_UNPUBLISH,
    CHANGE_FILE_UPLOAD,
    CHANGE_FILE_UPDATE_INFO,

    CHANGE_IPBAN_ADD,
    CHANGE_IPBAN_REMOVE,

    CHANGE_ROLE_SAVE,
    CHANGE_ROLE_DELETE,

    CHANGE_USER_REGISTER,
    CHANGE_USER_PROFILE,

    CHANGE_USER_LOGIN,
    CHANGE_USER_PASSWORD,
    CHANGE_USER_DISPLAY_NAME,
    CHANGE_USER_EMAIL,
    CHANGE_USER_ROLES,
    CHANGE_USER_CONFIRM,
    CHANGE_USER_UNCONFIRM,
    CHANGE_USER_LOCK,
    CHANGE_USER_UNLOCK,

    REFRESH_ADMIN_CACHE,
    CHANGE_EXTJOBS_KILL,

    SAVE_AUDIT_EVENT,
    SAVE_STATISTIC_LOG
}
