package app.enums;

public enum Permissions {
    USER_LOGGED_IN,
    USER_LOGGED_OUT,

    PAGES_VIEW,
    UPLOAD_FILES,

    ADMIN_PAGE,

    ADMIN_DASHBOARD,

    ADMIN_USERS_VIEW,
    ADMIN_USERS_EDIT,
    ADMIN_USERS_ROLES,
    ADMIN_USERS_LOCK,
    ADMIN_USERS_UNLOCK,
    ADMIN_USERS_CONFIRM,
    ADMIN_USERS_UNCONFIRM,
    ADMIN_ROLES_VIEW,
    ADMIN_ROLES_EDIT,

    ADMIN_IPBAN_VIEW,
    ADMIN_IPBAN_EDIT,

    ADMIN_AUDIT_VIEW,

    ADMIN_LOGS_VIEW,

    ADMIN_CACHE_VIEW,
    ADMIN_CACHE_REFRESH,
    ADMIN_EXTJOBS_VIEW,
    ADMIN_EXTJOBS_KILL,

    ADMIN_FESTIVALS_ADD,
    ADMIN_FESTIVALS_EDIT,
    ADMIN_FESTIVALS_DELETE,

    ADMIN_PLACES_VIEW,
    ADMIN_PLACES_EDIT,

    ADMIN_FILES_PUBLISH,
    ADMIN_FILES_DELETE;

    public static Permissions[] SYSTEM = new Permissions[] {USER_LOGGED_IN, USER_LOGGED_OUT};
}
